sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: a
    password: 123456
  wechat:
    appid: wx8e5c156c81a796ce
    secret: c94932d21606b2f4e07e569860fcc01a

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: 
    access-key-secret: 
    bucket-name: sky-take-out-q
  redis:
    host: localhost
    port: 6379